name: Compile IPK

on:
  push:
    branches:
      - main  # 或者你想要触发编译的分支  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialization environment
        run: |
         sudo apt-get update
         sudo apt-get -y install curl git tar zstd

      - name: Set up OpenWrt SDK
        run: |
          wget -q https://archive.openwrt.org/releases/22.03.7/targets/x86/64/openwrt-sdk-22.03.7-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz -O SDK.tar.xz
          tar -Jxf SDK.tar.xz
          mv openwrt-sdk-22.03.7-x86-64_gcc-11.2.0_musl.Linux-x86_64 ./SDK
          cd SDK
          find ./ | grep Makefile | grep filebrowser | xargs rm -f
          git clone https://github.com/OldCoding/luci-app-filebrowser package/luci-app-filebrowser
          ./scripts/feeds update -a
          ./scripts/feeds install luci-app-filebrowser
          make menuconfig

      - name: Compile IPK package
        run: |
          cd SDK
          make package/luci-app-filebrowser/compile V=s
          find ./ | grep ipk | grep filebrowser

      - name: Upload IPK
        uses: actions/upload-artifact@main
        with:
          name: luci-app-filebrowser
          path: SDK/bin/packages/x86_64/*/*filebrowser*.ipk

      - name: Upload OpenWrt Firmware to Release
        id: release
        uses: ncipollo/release-action@main
        with:
          name: 1.2
          allowUpdates: true
          removeArtifacts: true
          tag: 1.2
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: SDK/bin/packages/x86_64/*/*filebrowser*.ipk
