name: Compile IPK

on:
  push:
    branches:
      - main  # 或者你想要触发编译的分支  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get -y install curl git tar zstd

      - name: Install OpenWrt SDK
        run: |
          curl -SLk --connect-timeout 30 --retry 2 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "./SDK.tar.bz2"
          tar xjf SDK.tar.bz2
          mv "OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64" "SDK"

      - name: Clone Filebrowser Source Codes
        run: |
          git clone https://github.com/OldCoding/luci-app-filebrowser ./SDK/package/luci-app-filebrowser
          ls SDK/package/*

      - name: Compile Filebrowser IPK
        run: |
          cd SDK
          ls
          find filebrowser
          make package/luci-app-filebrowser/compile V=99
          find *filebrowser*.ipk

      - name: Upload IPK
        uses: actions/upload-artifact@main
        with:
          name: luci-app-filebrowser
          path: /SDK/bin/ar71xx/packages/base/*filebrowser*.ipk


      - name: Upload OpenWrt Firmware to Release
        id: release
        uses: ncipollo/release-action@main
        with:
          name: 1.1
          allowUpdates: true
          removeArtifacts: true
          tag: 1.1
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: SDK/bin/packages/x86_64/*/*filebrowser*.ipk
